### ISSUE TITLE
Config error on Termux when specifying a port

### ISSUE THREAD

**Issue by YlanAllouche** [dbeley/mpdscrobble#2]
Hello,

Thanks for this much simpler utility. It has been working well on my computers so I decided to bring to the phone as well using Termux.
On launch I get the following:

```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/data/com.termux/files/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/data/com.termux/files/home/.local/lib/python3.9/site-packages/mpdscrobble-0.2.6-py3.9.egg/mpdscrobble/__main__.py", line 112, in <module>
  File "/data/data/com.termux/files/home/.local/lib/python3.9/site-packages/mpdscrobble-0.2.6-py3.9.egg/mpdscrobble/__main__.py", line 53, in main
  File "/data/data/com.termux/files/home/.local/lib/python3.9/site-packages/mpdscrobble-0.2.6-py3.9.egg/mpdscrobble/utils.py", line 21, in create_network
  File "/data/data/com.termux/files/usr/lib/python3.9/configparser.py", line 1257, in __getitem__
    raise KeyError(key)
KeyError: 'username'
```

I am using the same config file as my desktop except that I have to add a `[mpdscrobble]` section to be able to specify a port.
Specifying a port/host on my desktop returns the same error as well so it doesn't seem to be Termux specific.

**Comment by dbeley** [comment]
Hi, thanks for the bug report there was indeed an issue with the config file parsing.

I've just published a new release (v0.2.7), could you update `mpdscrobble` and retry?

Thanks!

**Comment by YlanAllouche** [comment]
Thanks a lot for the quick fix.
Everything works
